### ISSUE TITLE
Add Repo Maintainers to CODEOWNERS file

### ISSUE THREAD

**Issue by andrewb1269hg** [hashgraph/hedera-protobufs-java#160]
# Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Description**:

Update this repositories `.github/CODEOWNER` file to ensure that the repository maintainer
group(s) have full control of the files in this repository.

**Comment by andrewb1269hg** [comment]
We should modify .github/CODEOWNERS and include the catchall rule and the standard core rules.

The groups here should be:

@hashgraph/devops-ci
@hashgraph/release-engineering-managers
@hashgraph/developer-advocates

**Comment by rbarkerSL** [comment]
Need to replace @hashgraph/hedera-base with @hashgraph/platform-base

**Comment by steven-sheehy** [comment]
No, I don't think mirror node is needed in this repo. Protos originate in hedera-services and are synced to hedera-protobufs and hedera-protobufs-java. Mirror node should probably only approve upstream in hedera-services.
